export const settings = {
	seed: 1,
	tileSize: 128,
	terrainType: '',
	scale: 1000,
	heightMultiplier: 100,
	baseHeight: 30,
	octaves: 5,
	persistence: 0.3,
	lacunarity: 2,
	renderDistance: 8,
	wireframe: false,
	gridHelper: false,
	mode: 'orbit',
	fogEnabled: true,
	fogDistance: 2,
	waterEnabled: true,
	postProcessingEnabled: false,
	fxaaEnabled: false,
	bloomStrength: 0.28,
	bloomRadius: 0.35,
	bloomThreshold: 0.82,
	timeOfDay: 9,
	timeEnabled: false,
	timeScale: 0.1,
	season: 'spring',
};
