export const settings = {
	seed: 13,
	tileSize: 128,
	segments: 48,
	renderDistance: 8,
	heightScale: 56,
	wireframe: false,
	gridHelper: true,
	mode: 'orbit',
	fogDensity: 0.001,
	timeOfDay: 9,
	timeEnabled: false,
	timeScale: 0.1,
	season: 'spring',
};
